version: 2
jobs:
	build:
		docker:
			- image: circleci/python:3.6.1
		working_directory: ~/circleci_pep8
		steps:
			- checkout
			- restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
			- run:
				name: Install pep8
				command: pip install flake8
			- run:
				name: Linter
				command: flake 8 .
