version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install hatch and flake
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install hatch
            pip install flake8

      - run:
          name: Install requirements
          command: |
            . env/bin/activate
            pip install -r requirements.txt
      
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Autoformating
          command: |
            . env/bin/activate
            autopep8 --in-place --aggressive --aggressive --recursive circleci_pep8

      - run:
          name: Unused imports and variables
          command: |
            . env/bin/activate
            autoflake --in-place -r --remove-all-unused-imports --remove-unused-variables circleci_pep8

      - run:
          name: Linting
          command: |
            . env/bin/activate
            flake8 circleci_pep8
        
      - run:
          name: run tests
          command: |
            . env/bin/activate
            python -m unittest

      - store_artifacts:
          path: test-reports
          destination: test-reports