# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
    working_directory: ~/circleci-flake8

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install hatch
          command: sudo pip install hatch

			- run:
					name: Install flake8
					command: sudo pip install flake8

			- run:
					name: Linting
					command: flake8 .

			- run:
					name: Install deps
					command: hatch install

			- run:
					name: Run tests
					command: hatch test

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      # - run:
      #     name: run tests
      #     command: |
      #       . venv/bin/activate
      #       python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports