version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Initialize virtual environment
          command: |
            python3 -m venv env
            . env/bin/activate

      - run:
          name: Install requirements
          command: |
            . env/bin/activate
            pip install -r requirements.txt
      
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Autoformat
          command: |
            . env/bin/activate
            autopep8 --in-place --aggressive --aggressive --recursive circleci_pep8

      - run:
          name: Unused imports and variables
          command: |
            . env/bin/activate
            autoflake --in-place -r --remove-all-unused-imports --remove-unused-variables circleci_pep8

      - persist_to_workspace:
          root: env
          paths:
            - .

      # - deploy:
      #     name: Deploy master in sequential workflow
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == master ]; then
      #         . env/bin/activate
      #         echo "Deploying to aws"
      #       else
      #         echo "Not master to deploying"
      #       fi



  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: env
      - run:
          name: Linting
          command: |
            . env/bin/activate
            flake8 circleci_pep8
          
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: env
      - run:
          name: Tests
          command: |
            . env/bin/activate
            python -m unittest

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: env
      - run:
          name: Fake deploy
          command: echo "Hello World"


workflows:
  version: 2
  dev:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
            - lint
          filters:
            branches:
              only:
                - master
                - release